### ISSUE TITLE
Can't resolve filters because unique class (resolveFilters)

### ISSUE THREAD

**Issue by ttungbmt** [outl1ne/nova-detached-filters#19]
![image](https://user-images.githubusercontent.com/12232155/123732551-43589300-d8c4-11eb-83cb-ac4b46af569a.png)

**Comment by KasparRosin** [comment]
Quick fix would be to either create separate classes for those two filters or pass in `->key('your_attribute_name')`

So for your example
```php
(new MultiselectFilter())->key('phanloai_cl')
(new MultiselectFilter())->key('noi_ph')
```
