### ISSUE TITLE
[2.x] Two of the same filters are out of sync

### ISSUE THREAD

**Issue by KasparRosin** [outl1ne/nova-detached-filters#29]
Two of the same filters are out of sync.

Example:
1. Use the same filter in dropdown filters and card.
2. Change the value of one of them
3. Observe that the other filter will have the old value.

**Comment by bocanhcam** [comment]
Seem like this issue still can't be fixed after 2 years.

**Comment by KasparRosin** [comment]
@bocanhcam I think due to how the laravel core logic works, it would be a rather hacky solution. 
Luckly this issue does not affect most users.
