### ISSUE TITLE
[2.x] Single filter reset does not update the displayed value.

### ISSUE THREAD

**Issue by philipbaginski** [outl1ne/nova-detached-filters#31]
Hi!

Testing strongly filters and what is found:

All filters are detached and are shown only in the card. In the filters popup is no filters. When I apply filter's, in the Nova filters place number of applied filters is displayed e.g. 2. All is find. But when I try to reset one of the filter - to the filter is added ->withMeta(['withReset' => true]) - the reset works, but the choose field still is displaying applied value. The only way to clean this field is to use global reset or reset filters using Nova filters space.

How to solve it?

**Comment by KasparRosin** [comment]
This is probably the same issue referenced in #26 and which i opened a pull-request (now discussion) for in nova-issues [#4508](https://github.com/laravel/nova-issues/discussions/4508)
