### ISSUE TITLE
laravel/framework: ^9.0 requirement for 2.0, was it really necessary ?

### ISSUE THREAD

**Issue by vesper8** [outl1ne/nova-detached-filters#32]
Not of all us have the luxury of upgrading to new Framework as we need to wait for many many dependencies to catch up. Since Laravel Nova 4.0 explicitly supports both Laravel 8 and 9, was it really necessary to slap on this 9.0 requirement on your 2.0 ?

I'm going to try forking it now... if this was just an after thought, please consider changing the requirement to `^8.0|^9.0`

Many thanks

**Comment by vesper8** [comment]
Just a quick follow-up, I forked your 2.0 release and made this one tiny modification to the composer.json `"laravel/framework": "^8.0|^9.0",` and everything seems to work just fine.

Please consider making this modification.. in the spirit of Nova 4 itself supporting Laravel 8.0 as well as 9.0. I'd have to have to maintain and update a fork just for this tiny modification.

Thank you

**Comment by KasparRosin** [comment]
![image](https://user-images.githubusercontent.com/33309407/179482645-ff096f1d-e537-4ca5-9cb0-85a695122f8d.png)

The decision was mostly done to match with the laravel's php requirements, since 2.0 supports php8.0 and higher.

**Comment by KasparRosin** [comment]
Removed the requirement in 2.0.1

**Comment by vesper8** [comment]
@KasparRosin thank you!!
