### ISSUE TITLE
Width class not existing

### ISSUE THREAD

**Issue by philipbaginski** [outl1ne/nova-detached-filters#34]
I'm trying to set up the width some of the filter and: w-1/5 works but w-1/6 does not work. What should I do to make it workable?

**Comment by professor93** [comment]
You can use only these sizes for cards in Laravel Nova 4:
`1/3, 2/3, 1/2, 1/4, 3/4, or full`

**Comment by philipbaginski** [comment]
One more :-) 1/5 works for me, but I need 1/6  :-) Any idea how to add it?

**Comment by ndrez-outl1ne** [comment]
[nova-grid](https://github.com/outl1ne/nova-grid) has some additional widths, including w-1/6. This should work: 

`FooFilter::make()->withMeta(['width' => 'w-1/6'])`
