### ISSUE TITLE
Can this filter work with relationship?

### ISSUE THREAD

**Issue by bocanhcam** [outl1ne/nova-detached-filters#46]
Let's say I have `Order` resource that has a relationship one to many with `OrderItem`.

`OrderItem` will not be shown without the context of `Order`.

That means I must see `OrderItem` in the `Order` detail page.

So I want to show the detached filter of `OrderItem` in the  `Order` detail page.

Is it possible?

**Comment by KasparRosin** [comment]
This package just appliess the visual and some slight enhancements to store filters.
The filter logic itself comes from nova's core. 

Since the query you write is within your own hands, I don't see any reason why you couldn't.
